/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compilerex;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Library {

	private static final Logger logger = LoggerFactory.getLogger(Library.class);

	public static void main(String[] args) {
		logger.info("Info message.");
		logger.debug("Debug message.");
	}

	public boolean someLibraryMethod() {
		return true;
	}
}
